travis:
  secure:
    BINSTAR_TOKEN: jpkLA4KH5fYgEthG9x5CQZkvRN/w5/gJofMNYKiFTX+RmGRjb2QTFDz6x10W+rzMeSR2l6xVuKll0w3C4k+0DXLivSGtkCFNaWbBkZu2ametRpK6wQhzLYCMrzihA7bbOlTwtZCFh9WgWxW0j0ua8YQHbu4as8KHQlwoulc/OMUa7QkLwGH4WaOzCgoJzqiYBNM+oJNTpdN6Dr8qVAqtKNU6QeyY+1e8segSX68JwS92UvaBD3Q5qeu1y25aFE7Rxa40VG1hs+FhdIvbOQOBbUo4WLIZDC7oy/XReNHz7r7QfmF4JhsREDOxkwWYZYFikEMWkwbyqhRzrdr1m7cmHVMBJQ0L5DuMC1IhKi+Swbu9i8CcbUdkt16UHZqpFJNzlFKricBAxJcTkjwF1E6wu2t2m94hhpAh6/JtWGR/2Ewi+x3T3mgNdq+UmlG5v2XUOceVHZvigp6KvAQp63xzFiCVVfeHtb20alqUQRQik0xXQZR0A5RE8dw6fEnMy/QLkrO89fNupCdTG0HblJoXBGKgt2HK4dqgbzWzHj3CZ9zFk3569PpCc6P51afdcplTjj2ZX4yDtwG4xR2CGpOO5ot6sluLprGAwCSRcEDoSvW+l2b64DlXncyzZYUkDqiVJYHv8e3B2MDY0h6UPwR687M8h07Wmrn0PrfGKCgy3dU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
